### ISSUE TITLE
mcr.microsoft.com hanging: pulling images failed

### ISSUE THREAD

**Issue by lucasassisrosa** [microsoft/containerregistry#165]
Hi there,

we're having issues since yesterday on pulling images from `mcr.microsoft.com`. It's hanging forever or failing with `connection reset`.

Image we're trying to pull now is: `mcr.microsoft.com/playwright:v1.37.0-focal@sha256:76de21fcd165e867021bc510c7cdf1811b68b518ba11a2101c3ec7d737eed831`. We also tried with a different playwright version.

Issue log:

```bash  
20:23:31  #8 sha256:d4ba1144e798cf86d9cad1dc30c84fdab2122da75494e92b92b298f10276b224 83.89MB / 568.48MB 235.7s
20:23:57  #8 sha256:d4ba1144e798cf86d9cad1dc30c84fdab2122da75494e92b92b298f10276b224 0B / 568.48MB 261.0s
20:24:02  #8 sha256:d4ba1144e798cf86d9cad1dc30c84fdab2122da75494e92b92b298f10276b224 14.68MB / 568.48MB 266.0s
20:24:07  #8 sha256:d4ba1144e798cf86d9cad1dc30c84fdab2122da75494e92b92b298f10276b224 14.68MB / 568.48MB 271.2s
20:24:12  #8 sha256:d4ba1144e798cf86d9cad1dc30c84fdab2122da75494e92b92b298f10276b224 14.68MB / 568.48MB 276.2s
20:24:17  #8 sha256:d4ba1144e798cf86d9cad1dc30c84fdab2122da75494e92b92b298f10276b224 14.68MB / 568.48MB 281.4s
20:24:22  #8 sha256:d4ba1144e798cf86d9cad1dc30c84fdab2122da75494e92b92b298f10276b224 14.68MB / 568.48MB 286.6s
20:24:25  #8 ERROR: failed to copy: read tcp 10.97.134.229:39880->150.171.69.10:443: read: connection reset by peer
20:24:25  ------
20:24:25   > [build 1/6] FROM mcr.microsoft.com/playwright:v1.37.0-focal@sha256:76de21fcd165e867021bc510c7cdf1811b68b518ba11a2101c3ec7d737eed831:
20:24:25  ------
20:24:25  failed to copy: read tcp 10.97.134.229:39880->150.171.69.10:443: read: connection reset by peer
```

**Comment by bsallesp** [comment]
#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 1.08kB 0.0s done
#1 DONE 0.0s

#2 [internal] load metadata for mcr.microsoft.com/dotnet/sdk:8.0
#2 ERROR: failed to do request: Head "https://mcr.microsoft.com/v2/dotnet/sdk/manifests/8.0": EOF

#3 [internal] load metadata for mcr.microsoft.com/dotnet/aspnet:8.0
#3 ERROR: failed to do request: Head "https://mcr.microsoft.com/v2/dotnet/aspnet/manifests/8.0": EOF
------
 > [internal] load metadata for mcr.microsoft.com/dotnet/sdk:8.0:
------
------
 > [internal] load metadata for mcr.microsoft.com/dotnet/aspnet:8.0:
------
Dockerfile:3
--------------------
   1 |     #See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.
   2 |     
   3 | >>> FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
   4 |     USER root
   5 |     WORKDIR /app
--------------------
ERROR: failed to solve: mcr.microsoft.com/dotnet/aspnet:8.0: failed to resolve source metadata for mcr.microsoft.com/dotnet/aspnet:8.0: failed to do request: Head "https://mcr.microsoft.com/v2/dotnet/aspnet/manifests/8.0": EOF

View build details: docker-desktop://dashboard/build/default/default/pgs4yqanfnc4gkq08vsrbq6a2
C:\Users\bsall\source\repos\Quiztle\Quiztle.API\Dockerfile(0,0): Error CTC1014: Docker command failed with exit code 1.
#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 1.08kB 0.0s done
#1 DONE 0.0s

#2 [internal] load metadata for mcr.microsoft.com/dotnet/sdk:8.0
#2 ERROR: failed to do request: Head "https://mcr.microsoft.com/v2/dotnet/sdk/manifests/8.0": EOF

#3 [internal] load metadata for mcr.microsoft.com/dotnet/aspnet:8.0
#3 ERROR: failed to do request: Head "https://mcr.microsoft.com/v2/dotnet/aspnet/manifests/8.0": EOF


thats my case

**Comment by AndreHamilton-MSFT** [comment]
Sorry for the delay. For those facing issues is it intermittent or consistent? Can you run the following

@lucasassisrosa:
```
curl -A github165 -v mcr.microsoft.com/v2/playwright:v1.37.0-focal/manifests/sha256:76de21fcd165e867021bc510c7cdf1811b68b518ba11a2101c3ec7d737eed831
```

@bsallesp
```
curl -A github165 -v https://mcr.microsoft.com/v2/dotnet/sdk/manifests/8.0
```

In the output of the curl command succeeded you should see an x-msedge-reg value. If you can share that value it would be great. This will help us narrow down where this issue is occurring. Also run it a few times so we have a few values to look into.

![image](https://github.com/user-attachments/assets/405cf65f-4e05-46ee-bf8b-bad789dad903)

**Comment by adanbrownpaca** [comment]
Same issue here guys, any updates? Running these curl commands result in:

* Host mcr.microsoft.com:443 was resolved.
* IPv6: 2603:1061:f:101::10, 2603:1061:f:100::10
* IPv4: 150.171.70.10, 150.171.69.10
*   Trying [2603:1061:f:101::10]:443...
* Connected to mcr.microsoft.com (2603:1061:f:101::10) port 443
* schannel: disabled automatic use of client certificate
* ALPN: curl offers http/1.1
* Send failure: Connection was reset
* schannel: failed to send initial handshake data: sent -1 of 292 bytes
* Closing connection
* schannel: shutting down SSL/TLS connection with mcr.microsoft.com port 443
* Send failure: Connection was reset
* schannel: failed to send close msg: Failed sending data to the peer (bytes written: -1)
curl: (35) Send failure: Connection was reset

**Comment by bsallesp** [comment]
Sorry for late, guys.

I forgot to say that, downgrading the docker, it worked.
I am using the version below:

![image](https://github.com/user-attachments/assets/ef890bf8-40b2-41b5-985c-b386d240d3ee)

**Comment by bsallesp** [comment]
Looks like a docker desktop issue.

**Comment by bsallesp** [comment]
> Sorry for the delay. For those facing issues is it intermittent or consistent? Can you run the following
> 
> @lucasassisrosa:
> 
> ```
> curl -A github165 -v mcr.microsoft.com/v2/playwright:v1.37.0-focal/manifests/sha256:76de21fcd165e867021bc510c7cdf1811b68b518ba11a2101c3ec7d737eed831
> ```
> 
> @bsallesp
> 
> ```
> curl -A github165 -v https://mcr.microsoft.com/v2/dotnet/sdk/manifests/8.0
> ```
> 
> In the output of the curl command succeeded you should see an x-msedge-reg value. If you can share that value it would be great. This will help us narrow down where this issue is occurring. Also run it a few times so we have a few values to look into.
> 
> ![image](https://private-user-images.githubusercontent.com/40181455/353165994-405cf65f-4e05-46ee-bf8b-bad789dad903.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1NDEyMzksIm5iZiI6MTcyMjU0MDkzOSwicGF0aCI6Ii80MDE4MTQ1NS8zNTMxNjU5OTQtNDA1Y2Y2NWYtNGUwNS00NmVlLWJmOGItYmFkNzg5ZGFkOTAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDE5MzUzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhNGExNWM4MTZiMzdhZWFiZGRmYjM0MDA1MTllMzJlNjRjYTE1MDRjN2UyNjdiN2E1YWQ2ZDQ1ZGY2MDFmOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ckK--zoYvYJiwNCFF-pwYQ5xx8jE4EoJGzCItWs3ypU)

![image](https://github.com/user-attachments/assets/17dcc1d8-3410-40fc-810b-1d8cdaae0aea)

**Comment by adanbrownpaca** [comment]
It is consistent. I will downgrade my version to 4.32 to confirm that it is a docker desktop issue. Stand by.

**Comment by adanbrownpaca** [comment]
Confirmed. Everything is stable using Docker Desktop version 4.32. Thanks - I will follow this thread for further updates and stay on 4.32 in the mean time.

**Comment by Matheus-SS** [comment]
I'm having the same problem right now building my images using jenkins and a linux machine. The only solution for me was to download the images before hand and build after that.
Im using mcr.microsoft.com/dotnet/aspnet:7.0 and mcr.microsoft.com/dotnet/sdk:7.0

**Comment by valentin-pouget-forge** [comment]
I downgraded to 4.32MacOS Silicon too, I was experiencing the following issues.

broken build because of a network issue only when OpenVPN was enabled: 
`failed to solve: node:20.16.0-alpine: failed to resolve source metadata for docker.io/library/node:20.16.0-alpine: failed to do request: Head "https://registry-1.docker.io/v2/library/node/manifests/20.16.0-alpine": dialing registry-1.docker.io:443 container via direct connection because app settings has no HTTPS proxy: connecting to registry-1.docker.io:443: dial tcp: lookup registry-1.docker.io: no such host`

connecting to an API endpoint from inside a running container was broken, and timeouting during the authentication endpoint. discovery from inside a running container:
`Error in callback: RPError: outgoing request timed out after 3500ms`

Authentication issues to pull images
`failed to solve: node:20.16-alpine: failed to resolve source metadata for [docker.io/library/node:20.16-alpine:](http://docker.io/library/node:20.16-alpine:) failed to authorize: failed to fetch anonymous token: Get "https://auth.docker.io/token?scope=repository%3Alibrary%2Fnode%3Apull&service=registry.docker.io": dial tcp: lookup [auth.docker.io](http://auth.docker.io/) on 127.0.0.11:53: server misbehaving`

**Comment by ggrafhalfbrick** [comment]
Any news on this without downgrading Docker?

**Comment by ggrafhalfbrick** [comment]
I ended up having to downgrade to 4.32.0 (157355). That works fine for us.
https://docs.docker.com/desktop/release-notes/

**Comment by cseuzaron** [comment]
Downgrade solved my problem as well, thank you!

**Comment by jabacrack** [comment]
I try to downgrade to 4.32.0 and switch off IPv6 - doesn't help.

**Comment by cesar-albusac** [comment]
Upgrading Docker Desktop (to 4.36.0) solved my issue

**Comment by jabacrack** [comment]
The problem was with my antivirus, after reinstalling the antivirus the docker started working.

**Comment by lucasassisrosa** [comment]
Upgraded Docker Desktop and it's solved now

v4.36.0

**Comment by adanbrownpaca** [comment]
> Upgraded Docker Desktop and it's solved now
> 
> v4.36.0

Lucas, are you confirming that v4.36 now works? Many of us had to downgrade to v4.32 to solve it. Is it now fully resolved?

**Comment by cesar-albusac** [comment]
For me downgrade to v4.32 to solve it :)

**Comment by TimothyHarrelson** [comment]
I have this problem on 4.34 to 4.36, only downgrading to 4.32 has solved the issue for me. 

I only see this issue on my work computer and not my home computer. My work computer uses a proxy (though it still fails to functions with the proxy disabled), and is on Windows 10, while my home computer is on WIndows 11.

**Comment by StormeNet** [comment]
Had this issue with v4.45, and solved it thx to @TimothyHarrelson by disabling IPv6 on my network adapter.

**Comment by brainwipe** [comment]
```
> docker pull mcr.microsoft.com/dotnet/aspnet:10.0
Error response from daemon: failed to resolve reference "mcr.microsoft.com/dotnet/aspnet:10.0": failed to do request: Head "https://mcr.microsoft.com/v2/dotnet/aspnet/manifests/10.0": EOF
```

Still not working on:

- Fresh Win 11 Pro, 10.0.26200 Build 26200
- Docker Desktop Version 4.65.0 (221669) on top of up-to-date WSL2
- Firewall/Antivirus paused, no affect

I'm not able to downgrade as ISO27001 and NCSC Cyber Essentials Plus requires we run the latest patched versions of software.

Disabling ipv6 on the network adapter does work around this issue but it feels like Microsoft Container Registry should investigate a fix.

**Comment by welyb-alegal** [comment]
Same problem here, everything up-to-date (Docker Desktop 4.66.1, Win 11 Pro 26200.8039) and no other problem but with Microsoft Container Registry. Unless IPv6 is disabled the time needed to pull needed images, we cannot pull images from mcr.microsoft.com which is a blocker when heavily working with devcontainers.

**Comment by jwood-billee** [comment]
Still a problem in 2026. Disabling IPv6 temporarily allow me to download the image.

```
* Host mcr.microsoft.com:443 was resolved.
* IPv6: 2603:1061:f:100::10, 2603:1061:f:101::10
* IPv4: 150.171.69.10, 150.171.70.10
*   Trying [2603:1061:f:100::10]:443...
* connect to 2603:1061:f:100::10 port 443 from :: port 62686 failed: Network unreachable
...
 X-MSEdge-Ref: Ref A: 79484B8EDF58488FADA4D48C74443F93 Ref B: ATL331000102023 Ref C: 2026-05-13T15:05:06Z
```
